run:
  timeout: 2m
  tests: false

issues:
  exclude-rules:
    - text: declaration of "err" shadows declaration
      linters:
        - govet
  exclude-dirs:
    - assets
    - proto
    - mocks
    - example*

linters-settings:
  govet:
    disable:
      - structtag
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 200
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  revive:
    rules:
      - name: "unused-parameter"
        disabled: true

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
      - commentedOutCode
      - octalLiteral

linters:
  disable-all: true
  enable:
    # - bodyclose
    # - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - goconst
    - godot
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    # - noctx
    - nolintlint
    - revive
    # - rowserrcheck
    - staticcheck
    # - structcheck
    - stylecheck
    - typecheck
    - unconvert
    # - unparam
    - unused
    - whitespace
    - wsl

    # don't enable:
    # - funlen
    # - gochecknoglobals
    # - gochecknoinits
    # - gocognit
    # - godox
    # - golint
    # - gomnd
    # - gosec
    # - lll
    # - maligned
    # - nestif
