project_name: outblocks

release:
  github:
    owner: outblocks
    name: outblocks-cli

before:
  hooks:
    - go mod download
    - make generate

builds:
  - binary: ok
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm
      - 386
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags: -s -w -X github.com/outblocks/outblocks-cli/internal/version.version={{.Version}} -X github.com/outblocks/outblocks-cli/internal/version.gitCommit={{.ShortCommit}} -X github.com/outblocks/outblocks-cli/internal/version.date={{.CommitDate}}

archives:
  - name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^dev:'
      - 'README'
      - Merge pull request
      - Merge branch

brews:
  - tap:
      owner: outblocks
      name: homebrew-tap
    name: ok
    folder: Formula
    homepage: https://outblocks.io
    description: Auto devops.
    license: MIT
    dependencies:
      - name: git
    install: |
      bin.install "ok"
      output = Utils.popen_read("#{bin}/ok completion bash")
      (bash_completion/"ok").write output
      output = Utils.popen_read("#{bin}/ok completion zsh")
      (zsh_completion/"_ok").write output
      output = Utils.popen_read("#{bin}/ok completion fish")
      (fish_completion/"ok.fish").write output
      prefix.install_metafiles
    test: |
      system "#{bin}/ok --version"

scoop:
  bucket:
    owner: outblocks
    name: outblocks-scoop
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: https://outblocks.io
  description: Auto devops.
  license: MIT

dockers:
  - id: alpine
    goos: linux
    goarch: amd64
    image_templates:
      - "outblocks/cli:latest"
      - "outblocks/cli:alpine"
      - "outblocks/cli:{{ .Tag }}"
      - "outblocks/cli:v{{ .Major }}"
      - "outblocks/cli:v{{ .Major }}.{{ .Minor }}"
    dockerfile: dockerfiles/Dockerfile.alpine
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
    extra_files:
      - dockerfiles/entrypoint.sh
