project_name: outblocks

release:
  github:
    owner: outblocks
    name: outblocks-cli

before:
  hooks:
    - go mod download
builds:
  - binary: ok
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm
      - 386
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags: -s -w -X internal.version.version={{.Version}} -X internal.version.gitCommit={{.ShortCommit}} -X internal.version.date={{.Date}}

archives:
  - name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^dev:'
      - 'README'
      - Merge pull request
      - Merge branch

brews:
  - tap:
      owner: outblocks
      name: homebrew-tap
    name: ok
    folder: Formula
    homepage: https://outblocks.io
    description: Auto devops.
    license: MIT
    dependencies:
      - name: git
    install: |
      bin.install "ok"
      output = Utils.popen_read("#{bin}/ok completion bash")
      (bash_completion/"ok").write output
      output = Utils.popen_read("#{bin}/ok completion zsh")
      (zsh_completion/"_ok").write output
      output = Utils.popen_read("#{bin}/ok completion fish")
      (fish_completion/"ok.fish").write output
      prefix.install_metafiles
    test: |
      system "#{bin}/ok --version"

scoop:
  bucket:
    owner: outblocks
    name: outblocks-scoop
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: https://outblocks.io
  description: Auto devops.
  license: MIT
