[git]

[git.config]
email = "semverbot@github.com"
name = "semverbot"

[git.tags]
prefix = "v"

[semver]
mode = "auto"

[semver.detection]
patch = ["fix/", "[fix]", "fix:", "alpha/", "alpha:", "alpha/", "alpha:"]
minor = ["feature/", "[feature]", "feat:", "feat/"]
major = ["release/", "[release]", "release:"]
